version: '3.8'

services:
  tml-classic-api:
    image: tml-classic-api
    container_name: tml-classic-api
    build:
      context: .
      dockerfile: KeklandBankSystem/Dockerfile
    ports: 
      - "5001:80"
    volumes:
      - /home/userImages:/app/wwwroot/imgs/userImages
      - /home/userImagesAds:/app/wwwroot/imgs/userImagesAds
      - /home/userImagesStatic:/app/wwwroot/imgs/userImagesStatic
      - /home/userImagesTicket:/app/wwwroot/imgs/userImagesTicket
      - /home/user_img:/app/wwwroot/imgs/user_img