version: '3.8'

services:
  tml-classic-db:
    image: postgres
    container_name: tml-classic-db
    ports:
      - 5433:5432
    networks:
      - database-network

  tml-classic-api:
    image: tml-classic-api
    container_name: tml-classic-api
    ports:
      - 59404:80
      - 44392:44392
    depends_on:
      - tml-classic-db
    networks:
      - database-network
    build:
      context: .
      dockerfile: KeklandBankSystem/Dockerfile

  tml-classic-proxy:
    ports:
      - 5001:44392

networks:
  database-network:
    driver: bridge