name: Build docker-file [ TEST conf. ]

on:
  push:
    branches: [dev]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: './docker-compose.test.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"tml-classic-api","appname":"tml-classic-test","apptype":"web"}]'