name: Build docker-file [ TEST conf. ]

on:
  push:
    branches: [dev]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.2.5
        with:
          docker_compose: 'docker-compose.test.yml' # required
          repo_token: "${{ secrets.PERSONAL_GH_TOKEN }}"