name: Build docker-file [ TEST conf. ]

on:
  push:
    branches: [dev]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create Container
        uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./docker-compose.test.yml"

      - name: Informatiion
        run: docker ps -a

      - name: Login to Heroku Container registry
        uses: actions/heroku@master
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login

      - name: Push
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:push -a tml-classic-test web

      - name: Release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a tml-classic-test web