name: Build docker-file [ TEST conf. ]

on:
  push:
    branches: [dev]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: publish
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.1.0
      with:
        compose-file: "./docker-compose.test.yml"